name: {{PLUGIN_FILE_NAME}}
description: {{PLUGIN_DESCRIPTION}}
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.0
